# Generated by Django 4.2 on 2023-06-02 14:45

import app.base.forms.fields
import app.base.forms.utils
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='begin_time',
            field=app.base.forms.fields.DateTimeField(default=app.base.forms.utils.datetime_now, verbose_name='Beginn'),
        ),
    ]
