# Generated by Django 4.2 on 2023-06-05 18:51

import app.base.forms.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_alter_booking_begin_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='time_stamp',
            field=app.base.forms.fields.DateTimeField(editable=False, verbose_name='Datum / Uhrzeit'),
        ),
    ]
